from enum import Enum


class INTERVIEW_STATUS(Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"


class EVALUATION_STATUS(Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"


class EVAL_STATUS_CODE(Enum):
    RATE_LIMIT_ERROR = 10001
    SERVICE_UNAVAILABLE_ERROR = 10002
    API_ERROR = 10003
    INVALID_REQUEST_ERROR = 10004
    TIME_OUT_ERROR = 10005
    INTERNAL_SERVER_ERROR = 10006
    API_CONNECTION_ERROR = 10007
    EVALUATION_ERROR = 10008
